### ISSUE TITLE
kafka: Extend unit tests

### ISSUE THREAD

**Issue by marclop** [elastic/apm-queue#123]
## Description

By leveraging the `kfake` package, we can provide pretty good test coverage for the unit tests. We should extend the current code coverage and add a few more tests in these areas:

### Producer

- Lossless graceful shutdown (No records should be lost when the producer is closed), both async and sync.

### Consumer

- At Most Once Delivery (default).
- At Least Once Delivery.
- Lossless graceful shutdown (No records should be lost when the consumer is closed).

**Comment by kruskall** [comment]
I have finished the Lossless graceful shutdown test and I have a few questions:

> (No records should be lost when the consumer is closed)

did you mean `when the producer is closed` ? I assumed that was a typo and I am closing the producer in the test. 

___

Could you clarify what we want to test with lossless graceful shutdown ?

This is the current test for the consumer graceful shutdown: 

https://github.com/elastic/apm-queue/blob/5e50011b202e23f36f222dff572af84ab2b5b9b6/kafka/consumer_test.go#L372

We produced some recorded and we're waiting for the consumer to process them. Once that's done we cancel the context:

https://github.com/elastic/apm-queue/blob/5e50011b202e23f36f222dff572af84ab2b5b9b6/kafka/consumer_test.go#L409-L415

The processor is unblocking the select by reading from the channel and incrementing the counter:

https://github.com/elastic/apm-queue/blob/5e50011b202e23f36f222dff572af84ab2b5b9b6/kafka/consumer_test.go#L389-L396

At that point the final assertion will make sure the counter match the produced recors:

https://github.com/elastic/apm-queue/blob/5e50011b202e23f36f222dff572af84ab2b5b9b6/kafka/consumer_test.go#L416

But this will always succeed because the processor was called and incremented the counter. If the processor is not called the test will timeout early.
My test is similar, except it is using the producer to create records. Apologies if I'm missing something obvious, I feel like the logic of tests is "verify that by closing the consumer after the consumer processed events, we are not losing events". I can't see that logic/test fails, wouldn't it always succeed ? How does shutdown relates to that ? Wouldn't shutdown happens in the middle of processing ? Or even before it ?

**Comment by kruskall** [comment]
Thank you for the clarification! :bow:

**Comment by kruskall** [comment]
I think this can be closed. All the tests mentioned in the description should be present.

@marclop Am I Missing something ?
